name: deputy_2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.1.0-262.2.beta <4.0.0"

dependencies:
    bot_toast: ^4.1.3
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.4
    google_fonts: ^6.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/nunito/

    fonts:
        - family: Nunito
          fonts:
              - asset: assets/nunito/Nunito-Black.ttf
                weight: 900
              - asset: assets/nunito/Nunito-BlackItalic.ttf
                weight: 900
                style: italic
              - asset: assets/nunito/Nunito-Bold.ttf
                weight: 700
              - asset: assets/nunito/Nunito-BoldItalic.ttf
                weight: 700
                style: italic
              - asset: assets/nunito/Nunito-ExtraBold.ttf
                weight: 800
              - asset: assets/nunito/Nunito-ExtraBoldItalic.ttf
                weight: 800
                style: italic
              - asset: assets/nunito/Nunito-ExtraLight.ttf
                weight: 200
              - asset: assets/nunito/Nunito-ExtraLightItalic.ttf
                weight: 200
                style: italic
              - asset: assets/nunito/Nunito-Italic.ttf
                style: italic
              - asset: assets/nunito/Nunito-Light.ttf
                weight: 300
              - asset: assets/nunito/Nunito-LightItalic.ttf
                weight: 300
                style: italic
              - asset: assets/nunito/Nunito-Medium.ttf
                weight: 500
              - asset: assets/nunito/Nunito-MediumItalic.ttf
                weight: 500
                style: italic
              - asset: assets/nunito/Nunito-Regular.ttf
              - asset: assets/nunito/Nunito-SemiBold.ttf
                weight: 600
              - asset: assets/nunito/Nunito-SemiBoldItalic.ttf
                weight: 600
                style: italic
