// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFTq28bTssDTBGV99tu5xnpHsuDzMNIDk',
    appId: '1:918422198087:web:7c3ed6832ed8b8ed049e62',
    messagingSenderId: '918422198087',
    projectId: 'deputy-640fb',
    authDomain: 'deputy-640fb.firebaseapp.com',
    storageBucket: 'deputy-640fb.appspot.com',
    measurementId: 'G-0188QNXSZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sOmX7S6bZnadgKpYGLfiRdmdEitcIQ0',
    appId: '1:918422198087:android:80b7d8093b6f62c5049e62',
    messagingSenderId: '918422198087',
    projectId: 'deputy-640fb',
    storageBucket: 'deputy-640fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRxcKbKbkdU7Bl1Uny3tBkx1YOEhljCA',
    appId: '1:918422198087:ios:a1b79052ec86c6ff049e62',
    messagingSenderId: '918422198087',
    projectId: 'deputy-640fb',
    storageBucket: 'deputy-640fb.appspot.com',
    iosBundleId: 'com.example.deputy2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRxcKbKbkdU7Bl1Uny3tBkx1YOEhljCA',
    appId: '1:918422198087:ios:a1b79052ec86c6ff049e62',
    messagingSenderId: '918422198087',
    projectId: 'deputy-640fb',
    storageBucket: 'deputy-640fb.appspot.com',
    iosBundleId: 'com.example.deputy2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFTq28bTssDTBGV99tu5xnpHsuDzMNIDk',
    appId: '1:918422198087:web:7c3ed6832ed8b8ed049e62',
    messagingSenderId: '918422198087',
    projectId: 'deputy-640fb',
    authDomain: 'deputy-640fb.firebaseapp.com',
    storageBucket: 'deputy-640fb.appspot.com',
    measurementId: 'G-0188QNXSZ4',
  );

}